
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SPECIAL = 11;
  public static final int STR_LITERAL = 12;
  public static final int EOF = 0;
  public static final int PREFIX = 5;
  public static final int CONCAT = 2;
  public static final int IF = 3;
  public static final int ELSE = 4;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int IDENTIFIER = 13;
  public static final int SUFFIX = 6;
  public static final int RBRACE = 9;
  public static final int LPAREN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONCAT",
  "IF",
  "ELSE",
  "PREFIX",
  "SUFFIX",
  "LPAREN",
  "RPAREN",
  "RBRACE",
  "COMMA",
  "SPECIAL",
  "STR_LITERAL",
  "IDENTIFIER"
  };
}

